// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqQX-JeaucnAy7vUhmIgLDAHjjE9uDBt4',
    appId: '1:794763581885:web:8cad5a1ddd162232539ad4',
    messagingSenderId: '794763581885',
    projectId: 'loginappiquitosstore',
    authDomain: 'loginappiquitosstore.firebaseapp.com',
    storageBucket: 'loginappiquitosstore.appspot.com',
    measurementId: 'G-Q1FMMF054T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD48UTQEHbWNVsb1dg8k0bnCPQKAG6OyU8',
    appId: '1:794763581885:android:7213efeb817db21f539ad4',
    messagingSenderId: '794763581885',
    projectId: 'loginappiquitosstore',
    storageBucket: 'loginappiquitosstore.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqGKZQmwAWgl0fE4DBK1T9tct3rvBwb8Y',
    appId: '1:794763581885:ios:9f7be26c1a6cd93f539ad4',
    messagingSenderId: '794763581885',
    projectId: 'loginappiquitosstore',
    storageBucket: 'loginappiquitosstore.appspot.com',
    iosClientId: '794763581885-n3i0b51ub1sjh47nntmk1j6i7m01c895.apps.googleusercontent.com',
    iosBundleId: 'com.example.iqtsStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqGKZQmwAWgl0fE4DBK1T9tct3rvBwb8Y',
    appId: '1:794763581885:ios:9f7be26c1a6cd93f539ad4',
    messagingSenderId: '794763581885',
    projectId: 'loginappiquitosstore',
    storageBucket: 'loginappiquitosstore.appspot.com',
    iosClientId: '794763581885-n3i0b51ub1sjh47nntmk1j6i7m01c895.apps.googleusercontent.com',
    iosBundleId: 'com.example.iqtsStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqQX-JeaucnAy7vUhmIgLDAHjjE9uDBt4',
    appId: '1:794763581885:web:d6020d345b55a3ce539ad4',
    messagingSenderId: '794763581885',
    projectId: 'loginappiquitosstore',
    authDomain: 'loginappiquitosstore.firebaseapp.com',
    storageBucket: 'loginappiquitosstore.appspot.com',
    measurementId: 'G-KBY4R9HQD7',
  );
}
